#Build and run basic tests on pull requests 
name: Build and test PRs on mysql-server repo

#Trigger workflow on pull requests to trunk branch of repo
on:
  pull_request:
    branches: [ "trunk" ]

jobs:
#Build on ubuntu
  ubuntu-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v6

    - name: Install Dependencies 
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make gcc g++ perl bison libtirpc-dev libssl-dev libncurses-dev default-jdk maven

    - name: Configure the Distribution
      run: |
        cmake -S . -B build -DWITH_ROUTER=0 -DWITH_MLE=1

    - name: Build the Distribution
      working-directory: build
      run: make -j$(nproc) 2>&1 | tee ../build.log

    - name: Run Tests
      working-directory: build/mysql-test
      run: |
          perl ./mysql-test-run.pl \
            --nounit-tests \
            --force \
            --mem \
            --retry-failure=2 \
            --retry=2 \
            --max-test-fail=0 \
            --report-unstable-tests \
            --clean-vardir \
            --parallel=32 \
            --do-suite=main \
            --timer \
            --xml-report="$GITHUB_WORKSPACE/mtr.xml" \
            --summary-report="$GITHUB_WORKSPACE/mtr-summary.txt" \
            2>&1 | tee ../../mtr.log
