name: Build and test PRs on mysql-server repo

on:
 pull_request:
   branches:
     - trunk

jobs:
 windows-build:
   runs-on: windows-latest

   steps:

   - uses: actions/checkout@v6

   - name: Find OpenSSL root
     run: |
        $opensslExe = (Get-Command openssl).Source
        $opensslRoot = Split-Path (Split-Path $opensslExe -Parent) -Parent
        echo "OPENSSL_ROOT=$opensslRoot" >> $env:GITHUB_ENV

   - name: Install Bison
     run: choco install winflexbison3 -y

   - name: Check Bison
     run: |
        where.exe bison
        bison --version    

   - name: Configure the Distribution
     run: |
        cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DWITH_SSL="$env:OPENSSL_ROOT"
