name: Build and test PRs on mysql-server repo

on:
 pull_request:
   branches:
     - trunk

jobs:
 windows-build:
   runs-on: windows-latest

   steps:

   - uses: actions/checkout@v6

   - name: Find OpenSSL root
     run: |
        $opensslExe = (Get-Command openssl).Source
        $opensslRoot = Split-Path (Split-Path $opensslExe -Parent) -Parent
        echo "OPENSSL_ROOT=$opensslRoot" >> $env:GITHUB_ENV

   - name: Install Bison
     run: choco install winflexbison3 -y

   - name: Expose Bison as bison.exe
     run: |
        $winBison = (Get-Command win_bison -ErrorAction SilentlyContinue).Source
        if (-not $winBison) { throw "win_bison not found" }
        Copy-Item $winBison "C:\ProgramData\chocolatey\bin\bison.exe" -Force    

   - name: Configure the Distribution
     run: |
        cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DWITH_SSL="$env:OPENSSL_ROOT"

   - name: Build the Distribution
     working-directory: build
     run: |
        cmake --build . --config RelWithDebInfo     

   - name: Run Tests
     working-directory: build/mysql-test
     run: |
        .\mysql-test-run.pl --force --timer --vs-config=RelWithDebInfo     
